Day 3, Topic 1,2 and 3 (Restart): Broadcasting – The Stretching Magic, practice, more practice

In [1]:
import numpy as np

In [4]:
#Problem 1.1
a = np.ones((5, 4))
b = np.arange(4)
result = a + b #Shape: (5, 4)
print(result.shape)

(5, 4)


In [8]:
a = np.ones((5, 4))
b = np.arange(5)
#result = a + b 
#It will not work because after right aligns the element 4 is not equal to 5

In [11]:
a = np.ones((5, 4))
b = np.arange(5).reshape(5, 1)
result = a + b
# What is result.shape? # 5, 4
print(result.shape)
print(result[0])

(5, 4)
[1. 1. 1. 1.]


In [12]:
a = np.ones((3, 1, 4))
b = np.arange(4)
result = a * b
# What is result.shape? #3, 1, 4
print(result.shape)

(3, 1, 4)


In [13]:
a = np.ones((3, 5, 4))
b = np.arange(5).reshape(5, 1)
result = a + b
# What is result.shape? #3, 5, 4
print(result.shape)

(3, 5, 4)


In [14]:
a = np.empty((2, 3, 4, 5))
b = np.empty((4, 5))
result = a + b
# shape? #2, 3, 4, 5
print(result.shape)

(2, 3, 4, 5)


In [15]:
a = np.empty((2, 3, 4, 5))
b = np.empty((3, 4, 1))
result = a * b
# shape? #2, 3, 4, 5
print(result.shape)

(2, 3, 4, 5)


In [16]:
a = np.empty((8, 1, 6, 1))
b = np.empty((7, 1, 5))
result = a - b
# shape? #8, 7, 6, 5
print(result.shape)

(8, 7, 6, 5)


In [17]:
a = np.empty((10, 1, 5))
b = np.empty((1, 20, 1))
result = a + b
# shape? #10, 20, 5
print(result.shape)

(10, 20, 5)


In [20]:
a = np.empty((1, 2, 1, 3))
b = np.empty((2, 1, 4))
# result = a * b
# shape? (Careful with alignment!)#No result no shape its not compatiable)

In [21]:
#Problem 3.1: Normalizing Image Batch
images = np.random.rand(32, 64, 64)
means = images.mean(axis=(1,2))
result = images - means[:, np.newaxis, np.newaxis]
print(result.shape)

(32, 64, 64)


In [23]:
#Problem 3.2: Outer Product with Broadcasting
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
result = x[:, np.newaxis] * y
print(result)
print(result.shape)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
(3, 3)


In [26]:
#Problem 3.3: Add a Bias to Each Channel (Channels First)
images = np.random.rand(16, 3, 32, 32)
bias = np.array([0.1, 0.2, 0.3])
result = images + bias[np.newaxis, :, np.newaxis, np.newaxis]
print(result.shape)

(16, 3, 32, 32)


In [28]:
#Problem 3.4: Add a Bias to Each Channel (Channels Last)
images = np.random.rand(16, 32, 32, 3)
bias = np.array([0.1, 0.2, 0.3])
result = images + bias
print(result.shape)

(16, 32, 32, 3)


In [30]:
a = np.ones((10, 5))
b = np.ones((10,))
c = a + b[:, np.newaxis] 
print(c.shape) # Is this correct? What is c.shape?

(10, 5)


In [31]:
a = np.ones((4, 5, 6))
b = np.ones((5, 6))
c = a + b  #shape : 4, 5, 6
print(c.shape)

(4, 5, 6)


In [33]:
a = np.ones((4, 5, 6))
b = np.ones((4, 6))
c = a + b[:, np.newaxis, :]
print(c.shape)

(4, 5, 6)


In [34]:
a = np.ones((3, 4))
b = np.ones((4, 3))
#incompatiable if we add them

In [35]:
#Problem 5.1: Manual Broadcast
b = np.arange(3)
expanded = np.broadcast_to(b, (4, 3))

In [36]:
#Problem 5.2: Using np.broadcast_arrays
x = np.array([[1], [2], [3]])   
y = np.array([10, 20, 30])
X, Y = np.broadcast_arrays(x, y)
print(x.shape)
print(y.shape)
print(x + y)

(3, 1)
(3,)
[[11 21 31]
 [12 22 32]
 [13 23 33]]
