Day 3, Topic 5: Advanced Ufunc Features

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3], dtype=np.int32)
b = np.array([1.1, 2.2, 3.3], dtype=np.float64)
c = np.add(a, b)
print(c.dtype)

float64


In [3]:
out_arr = np.empty(3, dtype=np.float32)
np.add(a, b, out=out_arr)

array([2.1, 4.2, 6.3], dtype=float32)

In [4]:
#Problem with idx
a = np.zeros(5)
idx = np.array([1, 2, 1, 3])
a[idx] += 1
print(a)   # [0. 1. 1. 1. 0.]   Wait, index 1 only got incremented once!

[0. 1. 1. 1. 0.]


In [5]:
#Solved with at
a = np.zeros(5)
idx = np.array([1, 2, 1, 3])
np.add.at(a, idx, 1)
print(a)

[0. 2. 1. 1. 0.]


In [6]:
# Simulate 10000 votes for 5 candidates (0-4)
votes = np.random.randint(0, 5, size=10000)
histogram = np.zeros(5, dtype=np.int32)
np.add.at(histogram, votes, 1)
print(histogram)

[1944 2121 1947 1971 2017]


In [7]:
arr = np.zeros((3, 4))
row_idx = np.array([1, 0, 2, 0])
col_idx = np.array([1, 3, 0, 1])
np.add.at(arr, (row_idx, col_idx), 1)
print(arr)

[[0. 1. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [20]:
#Custom Row‑Wise Mean Function
def row_mean(arr):
    return arr.mean(axis=-1)

row_mean_vec = np.vectorize(row_mean, signature='(n)->()')

data = np.random.rand(10, 5)
means = row_mean_vec(data)
print(means.shape)

(10,)


In [11]:
# Task 1: You have 100,000 random integers between 0 and 9.
# Use np.add.at to build a frequency histogram without loops.
arr = np.random.randint(0, 9, size=100_000)
histogram = np.zeros(9, dtype=np.int32)
np.add.at(histogram, arr, 1)
print(histogram)

[11164 11036 10965 11091 11244 11175 11063 11223 11039]


In [13]:
#Task 2: # Write a function row_range(arr) that returns max - min for each row.
# Use np.vectorize with signature to apply it to a 2D array.
def row_range(arr):
    return np.max(arr) - np.min(arr)

result = np.vectorize(row_range, signature='(n)->()')
arr_2d = np.random.rand(3, 4)
values = result(arr_2d)
print(values)


[0.54596836 0.32860457 0.70671542]


In [19]:
#Task 3: # Create a uint8 array of [255, 255, 255].
# Add 1 using np.add. What happens? (Overflow!)
# Now use np.add with casting='no'? Actually, use np.add.at to see overflow behavior.
arr = np.array([255, 255, 255], dtype=np.uint8)
result = np.add(arr, 1)
print(f"Original array: {arr}")
print(f"After adding one: {result}")
arr_at = np.array([255, 255, 255], dtype=np.uint8)
np.add.at(arr_at, [0, 1, 2], 1)
print(arr_at)

Original array: [255 255 255]
After adding one: [0 0 0]
[0 0 0]
