Day 1, Topic 4: Vectorization – Eliminating Python Loops

In [1]:
import numpy as np

In [2]:
a = np.arange(1_000_000)
b = np.arange(1_000_000)

In [3]:
result = a+b

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

In [11]:
print(a+b)
print(a*b)
print(a ** 2)

[11 22 33 44]
[ 10  40  90 160]
[ 1  4  9 16]


In [12]:
print(a > 2)

[False False  True  True]


In [13]:
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.        ]


In [16]:
print(a + 10)
print(a * 2)
print(a > 2.5)

[11 12 13 14]
[2 4 6 8]
[False False  True  True]


In [19]:
np.mean(a)

np.float64(2.5)

In [20]:
np.sum(a)

np.int64(10)

In [21]:
np.std(a)

np.float64(1.118033988749895)

In [22]:
np.max(a)

np.int64(4)

In [23]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8], [9, 10], [11, 12]])

In [24]:
diff = a - b

In [25]:
sq = diff ** 2

In [28]:
sum_rows = np.sum(sq, axis=1)

In [30]:
distance = np.sqrt(sum_rows)

In [31]:
distance

array([8.48528137, 8.48528137, 8.48528137])

In [33]:
distances = np.sqrt(np.sum((a - b) ** 2, axis=1))

In [34]:
distances

array([8.48528137, 8.48528137, 8.48528137])

In [47]:
a += b

In [48]:
a

array([[15, 18],
       [21, 24],
       [27, 30]])

In [45]:
result = np.empty_like(a)

In [46]:
np.add(a, b, out=result)

array([[15, 18],
       [21, 24],
       [27, 30]])

Activity

In [56]:
def compute_loop(prices, threshold):
    result = np.where(prices > threshold, prices * 1.1, prices * 0.9)
    return result

In [57]:
prices = np.array([10, 20, 30, 40, 50])
threshold = 20

In [58]:
compute_loop(prices, threshold)

array([ 9., 18., 33., 44., 55.])

Day 1, Topic 5: Gauntlet #1 – The Stride Predictor Challenge

In [59]:
arr = np.arange(24, dtype=np.int32).reshape(4, 6)

In [60]:
arr.shape

(4, 6)

In [61]:
arr.strides

(24, 4)

In [62]:
arr = np.arange(24, dtype=np.int32).reshape(4, 6)
sliced = arr[1:3, 2:5]

In [63]:
sliced.shape

(2, 3)

In [64]:
sliced.strides

(24, 4)

In [65]:
arr = np.arange(24, dtype=np.int32).reshape(4, 6)
stepped = arr[::2, ::3]

In [66]:
stepped.shape

(2, 2)

In [67]:
stepped.strides

(48, 12)

In [68]:
arr = np.arange(24, dtype=np.int32).reshape(4, 6)
reversed_arr = arr[::-1, ::-1]

In [69]:
reversed_arr.shape

(4, 6)

In [70]:
reversed_arr.strides

(-24, -4)

In [71]:
arr = np.arange(24, dtype=np.float64).reshape(2, 3, 4, order='F')

In [72]:
arr.shape

(2, 3, 4)

In [73]:
arr.strides

(8, 16, 48)