Day 2, Topic 2: np.where() – The Vectorized If‑Else

In [2]:
import numpy as np

In [3]:
data = np.array([-2, 5, 0, -7, 3, -1])
result = np.where(data > 0, "Positive", "Negative")

In [4]:
result

array(['Negative', 'Positive', 'Negative', 'Negative', 'Positive',
       'Negative'], dtype='<U8')

In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
mask = np.array([True, False, True, False])

In [6]:
result = np.where(mask, a, b)

In [7]:
result

array([ 1, 20,  3, 40])

In [8]:
data = np.array([-2, 5, 0, -7, 3, 1])

In [11]:
indeces = np.where(data > 0)

In [14]:
indeces

(array([1, 4, 5]),)

In [15]:
positive_num = data[indeces]

In [16]:
positive_num

array([5, 3, 1])

In [17]:
arr2d = np.array([[1, -2, -3],
                  [-4, 5, 6],
                  [7, -8, 9]])

In [18]:
row_index, col_index = np.where(arr2d > 0)

In [19]:
print("Row indices: ", row_index)
print("Col indices: ", col_index)

Row indices:  [0 1 1 2 2]
Col indices:  [0 1 2 0 2]


In [22]:
positive_numbers = arr2d[row_index, col_index]

In [23]:
positive_numbers

array([1, 5, 6, 7, 9])

In [24]:
data = np.array([-2, 5, 0, -7, 3, -1])
result = np.where(data > 0, "Positive", np.where(data < 0, "Negative", "Zero"))

In [25]:
result

array(['Negative', 'Positive', 'Zero', 'Negative', 'Positive', 'Negative'],
      dtype='<U8')

Grade classifier

In [47]:
def grade_classifier(scores):
    grades = np.where(scores >= 90, "A", np.where((scores >= 80), 
                                                  "B", np.where((scores >= 70), 
                                                                "C", np.where((scores >= 60), "D", "F"))))
    print("1. Score grades:", grades)
    pass_fail = np.where(scores >= 60, "Pass", "Fail")
    print("2. Pass or Fail:", pass_fail)
    indices_grade = np.where(scores >= 80)
    print("Indices of Grade A and B students:", indices_grade)

In [48]:
scores = np.array([45, 78, 92, 34, 67, 88, 55, 71])
grade_classifier(scores)

1. Score grades: ['F' 'C' 'A' 'F' 'D' 'B' 'F' 'C']
2. Pass or Fail: ['Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail' 'Pass']
Indices of Grade A and B students: (array([2, 5]),)
