Day 2, Topic 1: Boolean Masking – Filtering Data Without Loops

## 📘 Day 2, Topic 1: Boolean Masking — Filtering Data Without Loops

### What Is Boolean Masking?
A **boolean mask** is an array of `True`/`False` values that acts like a filter. When you apply it to an array, NumPy returns only the elements where the mask is `True`. This replaces the need for `if` statements inside `for` loops entirely.

### Step-by-step: How It Works
```python
temperatures = np.array([31, 22, 35, 18, 33, 27])

# Step 1: Create the mask
mask = temperatures > 30
# → [True, False, True, False, True, False]

# Step 2: Apply the mask
hot_days = temperatures[mask]
# → [31, 35, 33]    only where mask was True
```
You can also write it in one line: `temperatures[temperatures > 30]`

### Combining Conditions
Use **bitwise** operators (NOT Python's `and`/`or`/`not`!):

| Operator | Meaning | Example |
|----------|---------|---------|
| `&` | AND — both conditions true | `(a > 30) & (a < 35)` |
| `\|` | OR — at least one true | `(a < 20) \| (a >= 35)` |
| `~` | NOT — invert the mask | `~(a > 30)` |

> ⚠️ **Always wrap each condition in parentheses** when combining. `a > 30 & a < 35` is parsed as `a > (30 & a) < 35` — wrong!

### Modifying Values With a Mask
You can assign through a mask to change values in-place:
```python
temperatures[temperatures > 30] = 30   # cap all values at 30
```
This is the NumPy equivalent of: `for i in range(len(t)): if t[i] > 30: t[i] = 30`

### Counting & Aggregating With Masks
Boolean arrays are treated as **0/1 integers** by math functions:

```python
np.sum(temp > 30)    # counts how many elements satisfy the condition
np.any(temp > 30)    # True if at least one element satisfies
np.all(temp > 30)    # True if ALL elements satisfy
np.mean(temp > 30)   # proportion (fraction) that satisfy
```

### Boolean Masking on 2D Arrays
```python
grades = np.array([[85, 92], [45, 60]])

# Flat result — flattens the 2D array, returns 1D
grades[grades >= 90]   # → [92]

# Row-wise filtering — keep entire rows where condition holds for any column
grades[np.any(grades < 60, axis=1)]   # rows with at least one failing grade
grades[np.all(grades >= 60, axis=1)]  # rows where every grade passes
```
> 💡 `axis=1` means "check across columns (within each row)". `axis=0` means "check down rows (within each column)".

In [1]:
import numpy as np

In [2]:
temperatures = np.array([31, 22, 35, 18, 33, 27])

In [3]:
mask = temperatures > 30

In [4]:
print("Original temperatures: ", temperatures)
print("Temperatures mask: ", mask)

Original temperatures:  [31 22 35 18 33 27]
Temperatures mask:  [ True False  True False  True False]


In [5]:
hot_days = temperatures[mask]

In [6]:
print("Temp > 30: ", hot_days)

Temp > 30:  [31 35 33]


In [7]:
hot_days = temperatures[temperatures > 30]

In [8]:
hot_days

array([31, 35, 33])

In [9]:
comfortable_hot = temperatures[(temperatures > 30) & (temperatures < 35)]

In [10]:
comfortable_hot

array([31, 33])

In [11]:
extreme_days = temperatures[(temperatures < 20) | (temperatures >= 35)]

In [12]:
extreme_days

array([35, 18])

In [13]:
not_hot = temperatures[~(temperatures > 30)]

In [14]:
not_hot

array([22, 18, 27])

In [15]:
temperatures[temperatures > 30] = 30

In [16]:
temperatures

array([30, 22, 30, 18, 30, 27])

In [20]:
temp = np.array([31, 22, 35, 18, 33, 27])

In [21]:
count_days = np.sum(temp > 30)

In [22]:
print(count_days)

3


In [23]:
any_hot = np.any(temp > 30)

In [24]:
any_hot

np.True_

In [25]:
all_hot = np.all(temp > 30)

In [26]:
all_hot

np.False_

In [27]:
prop = np.mean(temp > 30)

In [28]:
prop

np.float64(0.5)

In [34]:
grades = np.array([[85, 92, 78],
                   [45, 60, 55],
                   [10, 20, 30],
                   [90, 88, 94]])

In [35]:
high_scores = grades[grades >= 90]

In [36]:
high_scores

array([92, 90, 94])

In [37]:
row_with_failures = grades[np.any(grades < 60, axis=1)]

In [38]:
row_with_failures

array([[45, 60, 55],
       [10, 20, 30]])

Practice Activity: Boolean Masking

In [61]:
def boolean_masking(sales):
     #Extract all days where sales were above $100.
    high_sales = sales[sales > 100]
    print("1. All days where sales were greater than $100: ", high_sales)
    #Extract all days where sales were between $90 and $200 inclusive.
    moderate_sales = sales[(sales >= 90) & (sales <= 200)]
    print("2. All days where sales were in between $90 and $200 inclusive: ", moderate_sales)
    #Count how many days had sales below $100.
    low_sales_days = np.sum(sales < 100) 
    print("3. No of days where Sales goes below $100: ", low_sales_days)
    #Create a new array where any sale below $100 is increased by 20% (modify in place).
    sales[sales < 100] *= 1.2
    print("4. Sales after 20% increase for low days:", sales)
    #Find the average of sales for days that were above $150.
    avg_sales = np.mean(sales[sales > 150])
    print("5. Average of sales above $150: ", avg_sales)

In [63]:
sales = np.array([120, 85, 210, 95, 300, 150, 75], dtype=np.float64)
boolean_masking(sales)

1. All days where sales were greater than $100:  [120. 210. 300. 150.]
2. All days where sales were in between $90 and $200 inclusive:  [120.  95. 150.]
3. No of days where Sales goes below $100:  3
4. Sales after 20% increase for low days: [120. 102. 210. 114. 300. 150.  90.]
5. Average of sales above $150:  255.0
