Day 2, Topic 3: Fancy Indexing with Integer Arrays

## 📘 Day 2, Topic 3: Fancy Indexing with Integer Arrays

### What Is Fancy Indexing?
**Fancy indexing** means using an **array of integers** (instead of a slice) to select elements. It lets you pick elements in **any order**, **repeat** elements, and index **non-contiguously** — things slicing can't do.

> ⚠️ **Fancy indexing ALWAYS returns a COPY** — never a view. Modifying the result does not affect the original.

---

### 1D Fancy Indexing
```python
arr = np.array([10, 20, 30, 40, 50])
arr[[1, 3, 4, 0]]   # → [20, 40, 50, 10]   # pick in any order, repeat allowed
```

---

### 2D Fancy Indexing — Three Patterns

**Pattern 1: Select whole rows**
```python
arr2d = np.arange(12).reshape(4, 3)
arr2d[[0, 2, 1, 0]]   # select rows 0, 2, 1, 0  (can repeat!)
```

**Pattern 2: Select whole columns**
```python
arr2d[:, [1, 0]]    # all rows, columns 1 and 0 (reordered)
```

**Pattern 3: Paired coordinates — pick specific (row, col) points**
```python
row_idx = np.array([1, 0, 3, 2])
col_idx = np.array([1, 1, 2, 0])
arr2d[row_idx, col_idx]    # picks: (1,1), (0,1), (3,2), (2,0)  → 4 individual elements
```
> The two index arrays are **paired element-by-element** — they must have the same shape. The result has the same shape as the index arrays.

---

### 3D Fancy Indexing
With a 3D array `arr_3d` of shape `(2, 3, 4)`:

```python
# Selecting whole 2D slices (blocks):
arr_3d[[1, 0, 1]]              # → shape (3, 3, 4) — three blocks

# Selecting specific rows from each block:
arr_3d[[1, 0], [2, 1]]         # paired: (block=1, row=2), (block=0, row=1) → shape (2, 4)

# Selecting specific single elements:
arr_3d[[1, 0, 1], [2, 0, 2], [3, 1, 1]]   # → 3 individual values
```

---

### `np.ix_()` — The Open Mesh (Cartesian Product Indexing)
Paired indexing picks **specific points**. `np.ix_()` picks **all combinations** (like a grid):

```python
blocks = np.array([0, 1])
rows   = np.array([2, 1])
cols   = np.array([3, 1])

# Paired: picks 2 specific points → shape (2,)
arr_3d[blocks, rows, cols]

# np.ix_: picks 2×2×2 = 8 combinations → shape (2, 2, 2)
arr_3d[np.ix_(blocks, rows, cols)]
```

Think of `np.ix_()` as: *"give me every block from [0,1], every row from [2,1], every column from [3,1]"* — the full Cartesian product.

---

### Fancy Indexing vs Slicing: View or Copy?

| Operation | Result | Memory |
|-----------|--------|--------|
| `arr[1:3]` | View | Shared memory |
| `arr[[1, 3]]` | **Copy** | Independent memory |
| `arr[:, [0, 2]]` | **Copy** | Independent memory |
| `arr[bool_mask]` | **Copy** | Independent memory |

```python
copy_fancy = original[[0], :, :]
copy_fancy[0, 1] = 99
original   # ← unchanged! fancy indexing made a copy
```

In [1]:
import numpy as np

In [3]:
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([1, 3, 4, 0])

In [4]:
result = arr[indices]

In [5]:
result

array([20, 40, 50, 10])

In [9]:
arr2d = np.arange(12).reshape(4, 3)

In [10]:
arr2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
row_indices = np.array([0, 2, 1, 0])
result = arr2d[row_indices]

In [12]:
result

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [15]:
col_indices = np.array([1, 0])
result_col = arr2d[:, col_indices]

In [16]:
result_col

array([[ 1,  0],
       [ 4,  3],
       [ 7,  6],
       [10,  9]])

In [ ]:
arr2d = np.arange(12).reshape(4, 3)

In [20]:
row_indices = np.array([1, 0, 3, 2])
col_indices = np.array([1, 1, 2, 0])
result = arr2d[row_indices, col_indices]

In [21]:
result

array([ 4,  1, 11,  6])

In [22]:
arr_3d = np.arange(24).reshape(2, 3, 4)
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [25]:
block_indices = np.array([1, 0, 1])
result = arr_3d[block_indices]

In [27]:
result.shape

(3, 3, 4)

In [28]:
block_idx = np.array([1, 1, 0])
row_idx = np.array([2, 0, 1])
result = arr_3d[block_idx, row_idx]

In [29]:
result

array([[20, 21, 22, 23],
       [12, 13, 14, 15],
       [ 4,  5,  6,  7]])

In [30]:
d_idx = np.array([1, 0, 1])
r_idx = np.array([2, 0, 2])
c_idx = np.array([3, 1, 1])

In [31]:
result = arr_3d[d_idx, r_idx, c_idx]

In [32]:
result

array([23,  1, 21])

In [35]:
block_idx = np.array([1, 0])
row_idx = np.array([2, 1])
result = arr_3d[block_idx, row_idx, :]

In [36]:
result

array([[20, 21, 22, 23],
       [ 4,  5,  6,  7]])

In [43]:
col_idx = np.array([1, 3, 0])
result = arr_3d[:1, :2, col_idx]

In [44]:
result

array([[[1, 3, 0],
        [5, 7, 4]]])

In [42]:
result.shape

(1, 3, 3)

In [45]:
row_selector = np.array([[0, 1],
                         [2, 0],
                         [1, 2]])

In [46]:
result = arr_3d[0, row_selector]

In [47]:
result

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

### 🔍 Proof: Fancy Indexing Creates Copies
The cells below demonstrate that a regular slice is a **view** (modifying it changes the original), while fancy indexing produces a **copy** (modifications are isolated).

Fancy indexing make copy

In [48]:
original = np.arange(24).reshape(2,3,4)

In [51]:
original

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [49]:
view_sliced = original[0, :, :2]

In [50]:
view_sliced

array([[0, 1],
       [4, 5],
       [8, 9]])

In [52]:
view_sliced[1, 0] = 10

In [53]:
original

array([[[ 0,  1,  2,  3],
        [10,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [54]:
copy_fancy = original[[0], :, :]

In [59]:
copy_fancy

array([[[ 0,  1,  2,  3],
        [10,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [62]:
copy_fancy[0, 1] = 99  # Sets the second row of the first block to 99

In [63]:
original

array([[[ 0,  1,  2,  3],
        [10,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [65]:
view_sliced.base is original.base

True

In [67]:
copy_fancy.base is original.base

False

In [68]:
arr_3d = np.arange(24).reshape(2, 3, 4)
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [73]:
block = np.array([0, 1])
row = np.array([2, 1])
col = np.array([3, 1])
result = arr_3d[np.ix_(block, row, col)]

In [74]:
result

array([[[11,  9],
        [ 7,  5]],

       [[23, 21],
        [19, 17]]])

3D Fancy Indexing

In [94]:
def fancy_indexing(sales):
    store_data = np.array([1])
    print("Extracting all the data of store A:\n", sales[store_data])
    row_data = np.array([2])
    print("Extracting all the data of Week 2 from both stores:\n", sales[:, row_data])
    print("Extracting Product 3 sales for Store 0, Week 1:", sales[0, 1, 3])
    store_data = np.array([[0, 0], [1, 1]])
    week_data = np.array([[0, 0], [2, 2]])
    product_data = np.array([[0, 2], [1, 3]])
    specific_data = sales[store_data, week_data, product_data]
    print("Extracting data from Store 0, Week 0, Products 0 and 2, Store 1, Week 2, Products 1 and 3:\n", specific_data)
    stores = np.array([0, 1])
    weeks = np.array([0, 2])
    products = np.array([1, 3])
    selected_data = sales[np.ix_(stores, weeks, products)]
    print("Shape of selected data: ", selected_data.shape)

In [95]:
sales = np.array([
    # Store 0
    [[100, 120, 140, 110],
     [130, 150, 160, 145],
     [170, 180, 190, 175]],
    # Store 1
    [[200, 220, 210, 205],
     [230, 240, 250, 235],
     [260, 270, 280, 265]]
])
fancy_indexing(sales)

Extracting all the data of store A:
 [[[200 220 210 205]
  [230 240 250 235]
  [260 270 280 265]]]
Extracting all the data of Week 2 from both stores:
 [[[170 180 190 175]]

 [[260 270 280 265]]]
Extracting Product 3 sales for Store 0, Week 1: 145
Extracting data from Store 0, Week 0, Products 0 and 2, Store 1, Week 2, Products 1 and 3:
 [[100 140]
 [270 265]]
Shape of selected data:  (2, 2, 2)
