Day 4, Topic 2: Compound Dtypes for RGB Images

In [1]:
import numpy as np

In [2]:
rgb_dtype = np.dtype([
    ('r', 'u1'),
    ('g', 'u1'),
    ('b', 'u1'),
])
img_structured = np.zeros((2, 2), dtype=rgb_dtype)
print(img_structured)

[[(0, 0, 0) (0, 0, 0)]
 [(0, 0, 0) (0, 0, 0)]]


In [3]:
img_structured[0, 0] = (255, 0, 0)
img_structured[0, 1] = (0, 255, 0)
img_structured[1, 0] = (0, 0, 255)
img_structured[1, 1] = (255, 255, 255)

In [4]:
img_structured

array([[(255,   0,   0), (  0, 255,   0)],
       [(  0,   0, 255), (255, 255, 255)]],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1')])

In [5]:
red_channel = img_structured['r']
print(red_channel)

[[255   0]
 [  0 255]]


In [6]:
red_channel[1, 0] = 128
print(img_structured)

[[(255,   0,   0) (  0, 255,   0)]
 [(128,   0, 255) (255, 255, 255)]]


In [10]:
# Simulate loading a 4x6 image (4 rows, 6 columns, 3 channels)
h, w = 4, 6
img_3d = np.random.randint(0, 256, size=(h, w, 3), dtype=np.uint8)
print(img_3d.shape)

(4, 6, 3)


In [13]:
img_struct = img_3d.view(rgb_dtype).reshape(h, w)
print(img_struct.shape)

(4, 6)


In [14]:
print(img_3d[0, 0])

[176 210 181]


In [16]:
img_struct[0, 0]['g'] = 255
print(img_3d[0, 0])

[176 255 181]


In [19]:
img_struct['r'] = np.clip(img_struct['r'] * 1.1, 0, 255)
img_struct['g'] = np.clip(img_struct['g'] * 1.1, 0, 255)
img_struct['b'] = np.clip(img_struct['b'] * 1.1, 0, 255)

In [21]:
red_mask = img_struct['r'] > 200
img_struct['r'][red_mask] = 255
img_struct['g'][red_mask] = 255
img_struct['b'][red_mask] = 255

In [23]:
temp = img_struct['r'].copy()
img_struct['r'] = img_struct['b']
img_struct['b'] = temp

In [25]:
gray = 0.299 * img_struct['r'] + 0.587 * img_struct['g'] + 0.114 * img_struct['b']

In [31]:
batch = np.random.randint(0, 256, size=(10, 64, 64, 3), dtype=np.uint8)
batch_struct = batch.view(rgb_dtype).reshape(batch.shape[:-1])
print(batch.shape)

(10, 64, 64, 3)


In [32]:
all_red = batch_struct['r']
print(all_red.shape)

(10, 64, 64)


In [ ]:
#Task: You have a 5×5 image as a regular 3D array with random colors.

In [34]:
#Task 1: Create a (5, 5, 3) array of random uint8 values (0–255).
imag_3d = np.random.randint(0, 256, size=(5, 5, 3), dtype=np.uint8)

In [36]:
#Task 2: View it as a structured array with fields 'r', 'g', 'b'.
imag_3d_struct = imag_3d.view(rgb_dtype).reshape((5, 5))

In [37]:
#Task 3: Print the shape of the structured array – it should be (5, 5).
print(f"Shape of structured array: {imag_3d_struct.shape}")

Shape of structured array: (5, 5)


In [40]:
#Task 4: Set all pixels where the red channel is > 200 to pure white (255, 255, 255). 
#Use a Boolean mask on the red channel and then assign to all three channels.
red_mask = imag_3d_struct['r'] > 200
imag_3d_struct['r'][red_mask] = 255
imag_3d_struct['g'][red_mask] = 255
imag_3d_struct['b'][red_mask] = 255

In [43]:
#Task 5: Compute the average color of the image (mean of each channel separately). 
#Print as (R_avg, G_avg, B_avg).
r_avg = imag_3d_struct['r'].mean()
g_avg = imag_3d_struct['g'].mean()
b_avg = imag_3d_struct['b'].mean()
print(f"Average color: ({r_avg:.2f}, {g_avg:.2f}, {b_avg:.2f})")

Average color: (149.00, 186.64, 184.08)


In [46]:
#Task 6: (Bonus) Swap the red and blue channels of the entire image using the structured view.
temp = imag_3d_struct['r'].copy()
imag_3d_struct['r'] = imag_3d_struct['b']
imag_3d_struct['b'] = temp