Day 4, Topic 4: Masked Arrays – Handling Missing, Invalid, or Unwanted Data

In [1]:
import numpy as np
import numpy.ma as ma

In [2]:
data = np.array([1, 2, -999, 3, 4])
mask = np.array([False, False, True, False, False])
marr = ma.MaskedArray(data, mask=mask)
print(marr)

[1 2 -- 3 4]


In [4]:
data = np.array([1, 2, -999, 3, 4])
marr = ma.masked_where(data == -999, data)
print(marr)

[1 2 -- 3 4]


In [5]:
data = np.array([1.0, 2.0, np.nan, 4.0, np.inf, 5.0])
marr = ma.masked_invalid(data)
print(marr)

[1.0 2.0 -- 4.0 -- 5.0]


In [6]:
data = np.array([1, 2, 4, 3, 4])
marr = ma.masked_equal(data, 4)
print(marr)

[1 2 -- 3 --]


In [9]:
data = np.array([1, 2, 4, 3, 4])
marr = ma.masked_less(data, 2)
print(marr)

[-- 2 4 3 4]


In [13]:
data = np.array([1, 2, -999, 3, 4])
marr = ma.masked_where(data == -999, data)
#keys methods that respect the mask: .mean(), .sum(), .std(), .var()
#.min(), .max(), .argmin(), .argmax()
#.prod(), .cumsum(), .cumprod()
print(marr.mean())

2.5


In [14]:
print(marr.data)
print(marr.mask)

[   1    2 -999    3    4]
[False False  True False False]


In [15]:
valid_values = marr.compressed()
print(valid_values)

[1 2 3 4]


In [16]:
valid_indices = np.where(~marr.mask)
print(valid_indices)

(array([0, 1, 3, 4]),)


In [17]:
filled = marr.filled(0)
print(filled)

[1 2 0 3 4]


In [18]:
data_2d = np.array([[1, 2, -999],
                    [4, -999, 5],
                    [-999, 7, 9]])
marr_2d = ma.masked_equal(data_2d, -999)
print(marr_2d)

[[1 2 --]
 [4 -- 5]
 [-- 7 9]]


In [19]:
col_mean = marr_2d.mean(axis=0)
print(col_mean)

[2.5 4.5 7.0]


In [21]:
images = np.random.randint(0, 256, size=(10, 64, 64), dtype=np.uint8)
images_masked = ma.masked_equal(images, 0)
mean_per_image = images_masked.mean(axis=(1, 2))

Task: You have a 2D array representing weekly sales data for 4 stores over 5 weeks. Missing or invalid entries are marked as -1

In [22]:
sales_data = np.array([
    [120, 150, -1, 130, 140],   # Store 0
    [200, -1, 210, 205, -1],    # Store 1
    [-1, 300, 310, -1, 320],    # Store 2
    [400, 410, 420, 430, 440]   # Store 3
])

In [23]:
#Create a masked array sales_masked where all -1 values are masked.
sales_masked = ma.masked_equal(sales_data, -1)

In [25]:
#Print the masked array. Verify that -1 values appear as --.
print("Filtered data:\n", sales_masked)

Filtered data:
 [[120 150 -- 130 140]
 [200 -- 210 205 --]
 [-- 300 310 -- 320]
 [400 410 420 430 440]]


In [34]:
#Compute the average weekly sales for each store (row means) ignoring missing weeks. 
#Print as a list of 4 numbers.
row_mean = sales_masked.mean(axis=1)
print("Weekly sales average: ", row_mean.tolist())

Weekly sales average:  [135.0, 205.0, 310.0, 420.0]


In [33]:
#Compute the total sales across all stores for each week (column sums) 
#ignoring missing values. Print as a list of 5 numbers.
col_sum = sales_masked.sum(axis=0)
print("Sum of all stores all week: ", col_sum.tolist())

Sum of all stores all week:  [720, 860, 940, 765, 900]


In [32]:
#Identify which stores have any missing data (i.e., their row mask contains at least one True). 
#Print their indices.
missing_indices = np.where(sales_masked.mask.any(axis=1))[0]
print("Missing data rows: ", missing_indices.tolist())

Missing data rows:  [0, 1, 2]


In [36]:
#Fill the missing values with the mean of that store's 
#available weeks and convert back to a regular NumPy array.
filled_arrays = sales_masked.filled(row_mean[:, np.newaxis])
print(filled_arrays)

[[120 150 135 130 140]
 [200 205 210 205 205]
 [310 300 310 310 320]
 [400 410 420 430 440]]
